### ISSUE TITLE
recursion limit compiler bug in newly released 1.6.0?

### ISSUE THREAD

**Issue by RagnarGrootKoerkamp** [Lokathor/wide#303]
Compiling my project on a new machine pulled in the new 1.6.0 version, and it suddenly stopped compiling.

A minimal breaking example is:

```rust
trait T<'s> {}
fn test<'s>(_x: impl T<'s>) {
    let _ = wide::u32x8::ZERO << wide::u32x8::ZERO;
}
```

This does work in 1.5.0, and also works when the `x` argument is removed, so it's more likely a compiler bug than a wide bug, but I wanted to report it anyway for now. (The error on 1.6.0 is with both nightly and stable, both before and after I did `rustup update`. The last time I ran that was 2 months ago, so if it really is a compiler error it has been around for a while.)

The error is:

```
error[E0275]: overflow evaluating the requirement `u32x8: Shl<&_>`
  --> src/anti_lex.rs:84:14
   |
84 |         zero << zero;
   |              ^^
   |
   = help: consider increasing the recursion limit by adding a `#![recursion_limit = "256"]` attribute to your crate (`seq_hash`)
   = note: required for `u32x8` to implement `Shl<&&_>`
   = note: 126 redundant requirements hidden
   = note: required for `u32x8` to implement `Shl<&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&&...>`
   = note: the full name for the type has been written to '/home/philae/git/eth/git/seq-hash/target/debug/deps/seq_hash-58d93db54d231564.long-type-14741644957531347869.txt'
   = note: consider using `--verbose` to print the full type name to the console

For more information about this error, try `rustc --explain E0275`.
```

**Comment by Lokathor** [comment]
It's very weird that removing the _x causes it to compile, when _x isn't in the expression.

**Comment by Noam2Stein** [comment]
Somehow because of the `impl T<'s>` parameter, the trait solver forgets that `impl Shl<u32x8> for u32x8` exists, and instead it thinks that only `impl<Rhs> impl Shl<&Rhs> for u32x8 where Self: Shl<Rhs, Output = Self>` exists, leading it to try to solve the trait bound recursively somehow leading to `Shl<&&&&&&&&&&&&_>` and an overflow.

This looks like a very weird type system bug. Could you open a Rust issue for this?

I simplified the context of this bug to not require `wide`:

```
use std::ops::Add;

pub struct Type;

impl Add for Type {
    type Output = Self;

    fn add(self, _: Type) -> Self::Output {
        unimplemented!()
    }
}

impl<Rhs> Add<&Rhs> for Type
where
    Self: Add<Rhs, Output = Self>,
{
    type Output = Self;

    fn add(self, _: &Rhs) -> Self::Output {
        unimplemented!()
    }
}

trait T<'s> {}
fn test<'s>(_x: impl T<'s>) {
    let _ = Type + Type;
}
```

The following changes make the code compile:

- Removing the `Add<&Rhs>` implementation
- Removing the `_x` function parameter
- Changing `impl T<'s>` to `impl T<'static>`
- Removing the `Output = Self` bound in the implementation of `Add<&Rhs>`
- Changing `Rhs` into a specific type (removing the generic parameter)

**Comment by RagnarGrootKoerkamp** [comment]
Yes, that matches what I was thinking.
Thanks for the self-contained reproducer; I'll go make a rust issue with that and link it back from here => See https://github.com/rust-lang/rust/issues/160276.

**Comment by Noam2Stein** [comment]
If this is causing a lot of problems downstream, the change can be reverted until the new trait solver is stabilized.

Even though the bug is in the compiler, the `wide` change triggering it is the compile time optimization made in #297. Note that reverting it would hurt compile times (I think its around 3s->4s on my machine).

Should we revert it?

**Comment by Lokathor** [comment]
Yeah, 3 back to 4 isn't that bad, and it's better to have no breakage than any chance of a break, even if it is a compiler-side bug.

Let's have a reversion PR and I'll issue a patch release.

**Comment by RagnarGrootKoerkamp** [comment]
(I'd make the revert as small as possible, only changing the specific breaking trait implementation to the (multiple) impls that were there before, and keeping all the current macro setup right?)
